# 使用 Node.js 官方镜像作为基础镜像
FROM node:18-alpine

# 设置工作目录
WORKDIR /app/package/web

# 复制根目录的 package.json 和 package-lock.json
COPY package*.json ../../

# 复制客户端的 package.json 和 package-lock.json
COPY package/web/package*.json ./

# 安装项目依赖
RUN npm install

# 复制客户端代码
COPY package/web .

# 构建客户端项目
RUN npm run build

# 暴露客户端运行的端口，假设为 4001
EXPOSE 4001

# 使用一个简单的静态服务器来运行 React 构建后的文件
RUN npm install -g serve
CMD ["serve", "-s", "build", "-l", "3002"]