version: '3'
services:
  nestjs-server:
    build:
      context: .
      dockerfile: package/server/dockerfile
    ports:
      - "4002:4002"
    restart: always
    volumes:
      - ../config.env:/config.env
  react-client:
    build:
      context: .
      dockerfile: package/web/dockerfile
    ports:
      - "4001:4001"
    restart: always
    volumes:
      - ../config.env:/app/config.env  # 将宿主机上的 config.env 挂载到容器内的 /app/config.env