version: '3.8'
services:
  # MongoDB 服务
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb:/data/db
    command: 
      - --auth
      - --bind_ip_all          # 允许所有 IP 连接
      - --wiredTigerCacheSizeGB=1
    networks:
      - j-table-network  # 使用明确的网络名

  nestjs-server:
    build:
      context: .
      dockerfile: package/server/dockerfile
    container_name: j-table-nestjs-server  # 明确指定容器名
    ports:
      - "4002:4002"
    restart: always
    volumes:
      - ../config.env:/config.env
    depends_on:
      - mongodb  # 确保 MongoDB 先启动
    networks:
      - j-table-network  # 使用相同的网络
    # 添加 DNS 配置
    dns:
      - 8.8.8.8
      - 114.114.114.114

  react-client:
    build:
      context: .
      dockerfile: package/web/dockerfile
    container_name: j-table-react-client
    ports:
      - "4001:4001"
    restart: always
    volumes:
      - ../config.env:/app/config.env
    depends_on:
      - nestjs-server  # 如果需要，可以添加这个依赖
    networks:
      - j-table-network

# 明确创建网络
networks:
  j-table-network:
    name: j-table-network
    driver: bridge