version: '3'
services:
  nestjs-server:
    build:
      context: ./package/server
      dockerfile: dockerfile
    ports:
      - "4002:4002"
    restart: always
  react-client:
    build:
      context: ./package/web
      dockerfile: dockerfile
    ports:
      - "4001:4001"
    restart: always