# 使用 Node.js 官方镜像作为基础镜像
FROM node:18-alpine

# 设置工作目录
WORKDIR /app/package/server

# 复制根目录的 package.json 和 package-lock.json
COPY package*.json ../../

# 复制服务端的 package.json 和 package-lock.json
COPY package/server/package*.json ./

# 安装项目依赖
RUN npm install

# 复制服务端代码
COPY package/server .

# 构建服务端项目
RUN npm run build

# 暴露服务端运行的端口，假设为 4002
EXPOSE 4002

# 启动服务端项目
CMD ["npm", "run", "start:prod"]